### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by nhy17-thu** [justanhduc/neuralnet-pytorch#8]
Hi, when I finished `git clone` and was running `python setup.py install --cuda-ext`, compiling error appears (please check [here](https://drive.google.com/file/d/1ncTavAzUs2xTtNpTqgeEgluz5fy0Lf6H/view?usp=sharing) for complete log).

@justanhduc Could you please help me to solve this question ASAP? I really need it in several days. My environment:
Ubuntu 18.04
Python 3.8.8
Pytorch 1.8.0
Cuda 11.1
GCC 9.3.0

**Comment by justanhduc** [comment]
Hi @nhy17-thu. Sorry for late answer. I have never tried Pytorch 1.8. The error indicates some matching function call, so possibly some API has been changed. Please downgrade your Pytorch to 1.7. I will investigate this problem soon.

**Comment by nhy17-thu** [comment]
> Hi @nhy17-thu. Sorry for late answer. I have never tried Pytorch 1.8. The error indicates some matching function call, so possibly some API has been changed. Please downgrade your Pytorch to 1.7. I will investigate this problem soon.

Hi, thanks for your response. Now I've successfully installed the cuda version of `neuralnet-pytorch` with PyTorch 1.7.1 and Cuda toolkit 11.0.
